// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZCDs2l_HAkzRJzGcYLZB6Dwk7F_k_E2c',
    appId: '1:634660190413:web:e694d6ce0606828de25184',
    messagingSenderId: '634660190413',
    projectId: 'flutter-project-1688b',
    authDomain: 'flutter-project-1688b.firebaseapp.com',
    storageBucket: 'flutter-project-1688b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMQs8DQCefiXsZdaonx8uhXvqKI0MilEg',
    appId: '1:634660190413:android:d9f09303977079c7e25184',
    messagingSenderId: '634660190413',
    projectId: 'flutter-project-1688b',
    storageBucket: 'flutter-project-1688b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPhokJ7RBRgOv7cpLEGWxXRjlihFYqsec',
    appId: '1:634660190413:ios:c92043fa00096892e25184',
    messagingSenderId: '634660190413',
    projectId: 'flutter-project-1688b',
    storageBucket: 'flutter-project-1688b.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPhokJ7RBRgOv7cpLEGWxXRjlihFYqsec',
    appId: '1:634660190413:ios:e0f1c28fc31c202fe25184',
    messagingSenderId: '634660190413',
    projectId: 'flutter-project-1688b',
    storageBucket: 'flutter-project-1688b.appspot.com',
    iosBundleId: 'com.example.chattingApp.RunnerTests',
  );
}
